### ISSUE TITLE
adding a excel format sample will be good

### ISSUE THREAD

**Issue by jamilxt** [Valhalla-TKT/Work-From-Home-System#26]
I'm confused which type of excel it is expecting? Can you please help me out?
![image](https://github.com/user-attachments/assets/6f708f54-0f79-4bcf-a85c-0d6365251f0f)

**Comment by thanthtooaung-coding** [comment]
Okay I will fix this. Thank you for your comment.

**Comment by jamilxt** [comment]
any update on this?

**Comment by thanthtooaung-coding** [comment]
You can reference excel format and necessary tools in this repository : [Link](https://github.com/thanthtooaung-coding/required-tools-for-work-from-home-system)
