### ISSUE TITLE
exact table name in native query

### ISSUE THREAD

**Issue by jamilxt** [Valhalla-TKT/Work-From-Home-System#28]
In case of Native Query, we should use the exact table name in query. Right now, we are using "User" where our table name is "user" in the database. That's why facing this issue while running the app from the "main" branch.

![image](https://github.com/user-attachments/assets/56aa577b-9a42-4018-ba49-fb510c487cab)

**Comment by jamilxt** [comment]
#27  this should fix the issue

**Comment by thanthtooaung-coding** [comment]
Thanks and now I'll currenly developing the branch wfhs_v2.2, I will fix this issue with that branch.
